version: '3.8'

services:
  sqlnode1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlnode1
    hostname: sqlnode1
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MewVmax.1
      - MSSQL_AGENT_ENABLED=true
      - MSSQL_ENABLE_HADR=1
    ports:
      - "1433:1433"
      - "5022:5022"
    networks:
      - sqlnet
    volumes:
      - sql1data:/var/opt/mssql
      - ./backups:/var/opt/mssql/backups  
    restart: unless-stopped

  sqlnode2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlnode2
    hostname: sqlnode2
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MewVmax.1
      - MSSQL_AGENT_ENABLED=true
      - MSSQL_ENABLE_HADR=1
    ports:
      - "1434:1433"
      - "5023:5022"
    networks:
      - sqlnet
    volumes:
      - sql2data:/var/opt/mssql
      - ./backups:/var/opt/mssql/backups  
    restart: unless-stopped

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"   
    networks:
      - sqlnet
    volumes:
      - influxdb_data:/var/lib/influxdb
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    volumes:
    - "C:/Users/maric/OneDrive/Documentos/compose/telegraf.conf:/etc/telegraf/telegraf.conf" 
    networks:
      - sqlnet
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"  
    networks:
      - sqlnet
    restart: unless-stopped

networks:
  sqlnet:
    driver: bridge

volumes:
  sql1data:
  sql2data:
  influxdb_data:
